fix manifest.json missing error
  % ./make.js package
  internal/modules/cjs/loader.js:638
      throw err;
      ^

  Error: Cannot find module './dist/vimium/manifest.json'
      at Function.Module._resolveFilename
  (internal/modules/cjs/loader.js:636:15)
      at Function.Module._load (internal/modules/cjs/loader.js:562:25)
      at Module.require (internal/modules/cjs/loader.js:692:17)
      at require (internal/modules/cjs/helpers.js:25:18)
      at Object.buildStorePackage [as fn] (/tmp/vimium/make.js:45:28)
      at Object.<anonymous> (/tmp/vimium/make.js:183:24)
      at Module._compile (internal/modules/cjs/loader.js:778:30)
      at Object.Module._extensions..js
  (internal/modules/cjs/loader.js:789:10)
      at Module.load (internal/modules/cjs/loader.js:653:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)